/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.2.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIWriteContractRequestArgsInner.h"

namespace MetaFab
{

/*
 * OpenAPIWriteContractRequest
 *
 * 
 */
class METAFAB_API OpenAPIWriteContractRequest : public Model
{
public:
    virtual ~OpenAPIWriteContractRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* A contract function name. This can be any valid function from the the ABI of the contract you are interacting with. For example, `mint`. */
	FString Func;
	/* An array of args. This is optional and only necessary if the function being invoked requires arguments per the contract ABI. For example, `[123, \"Hello\", false]`. */
	TOptional<TArray<OpenAPIWriteContractRequestArgsInner>> Args;
};

}
