/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIWalletsApi.h"

#include "OpenAPICreateWalletSignatureRequest.h"
#include "OpenAPITransactionModel.h"
#include "OpenAPIWalletModel.h"

namespace OpenAPI
{

/* Create wallet signature
 *
 * Creates a wallet signature from a plaintext message using the wallet for the provided walletId and walletDecryptKey. Wallet signatures cannot be generated for EOA wallets.
*/
class OPENAPI_API OpenAPIWalletsApi::CreateWalletSignatureRequest : public Request
{
public:
    virtual ~CreateWalletSignatureRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Any wallet id within the MetaFab platform. */
	FString WalletId;
	/* The `walletDecryptKey` for the provided `walletId`. */
	FString XWalletDecryptKey;
	OpenAPICreateWalletSignatureRequest OpenAPICreateWalletSignatureRequest;
};

class OPENAPI_API OpenAPIWalletsApi::CreateWalletSignatureResponse : public Response
{
public:
    virtual ~CreateWalletSignatureResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    FString Content;
};

/* Get wallet
 *
 * Returns a wallet object for the provided walletId.
*/
class OPENAPI_API OpenAPIWalletsApi::GetWalletRequest : public Request
{
public:
    virtual ~GetWalletRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Any wallet id within the MetaFab platform. */
	FString WalletId;
};

class OPENAPI_API OpenAPIWalletsApi::GetWalletResponse : public Response
{
public:
    virtual ~GetWalletResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIWalletModel Content;
};

/* Get wallet balances
 *
 * Returns the current native token balance for all chains supported by MetaFab for the provided walletId. This includes balances like Eth, Matic and other native tokens from chains MetaFab supports.
*/
class OPENAPI_API OpenAPIWalletsApi::GetWalletBalancesRequest : public Request
{
public:
    virtual ~GetWalletBalancesRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Any wallet id within the MetaFab platform. */
	FString WalletId;
};

class OPENAPI_API OpenAPIWalletsApi::GetWalletBalancesResponse : public Response
{
public:
    virtual ~GetWalletBalancesResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TMap<FString, double> Content;
};

/* Get wallet transactions
 *
 * Returns an array of MetaFab initiated transactions performed by the provided walletId. Transactions returned are ordered chronologically from newest to oldest.
*/
class OPENAPI_API OpenAPIWalletsApi::GetWalletTransactionsRequest : public Request
{
public:
    virtual ~GetWalletTransactionsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Any wallet id within the MetaFab platform. */
	FString WalletId;
};

class OPENAPI_API OpenAPIWalletsApi::GetWalletTransactionsResponse : public Response
{
public:
    virtual ~GetWalletTransactionsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<OpenAPITransactionModel> Content;
};

}
