/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.2.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace MetaFab
{

/*
 * OpenAPIBatchTransferCurrencyRequest
 *
 * 
 */
class METAFAB_API OpenAPIBatchTransferCurrencyRequest : public Model
{
public:
    virtual ~OpenAPIBatchTransferCurrencyRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* An array of valid EVM based addresses to transfer currency to. */
	TOptional<TArray<FString>> Addresses;
	/* An array of wallet ids within the MetaFab ecosystem to transfer currency to. */
	TOptional<TArray<FString>> WalletIds;
	/* An array of currency amounts to transfer. Ordering corresponds to the ordering of provided `addresses` and/or `walletIds`. If both `addresses` and `walletIds` are provided, `addresses` are first in the order. */
	TArray<double> Amounts;
	/* An optional array of uint256 numbers to reference each transfer in the batch. Ordering corresponds to the ordering of provided `addresses` or `walletIds`. If both `addresses` and `walletIds` are provided, `addresses` are first in the order. */
	TOptional<TArray<double>> References;
};

}
