/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.4.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITransactionModel.h"

namespace OpenAPI
{

/*
 * OpenAPISetPlayerConnectedWallet200Response
 *
 * 
 */
class OPENAPI_API OpenAPISetPlayerConnectedWallet200Response : public Model
{
public:
    virtual ~OpenAPISetPlayerConnectedWallet200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Id;
	TOptional<FString> Address;
	TOptional<OpenAPITransactionModel> Transaction;
};

}
