/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPICollectionItemAttributesInner.h"

namespace OpenAPI
{

/*
 * OpenAPICollectionItem
 *
 * 
 */
class OPENAPI_API OpenAPICollectionItem : public Model
{
public:
    virtual ~OpenAPICollectionItem() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* This field has not had a description added. */
	TOptional<FString> Id;
	/* This field has not had a description added. */
	TOptional<FString> Image;
	/* This field has not had a description added. */
	TOptional<FString> Name;
	/* This field has not had a description added. */
	TOptional<FString> Description;
	/* This field has not had a description added. */
	TOptional<FString> ExternalUrl;
	/* This field has not had a description added. */
	TOptional<TArray<OpenAPICollectionItemAttributesInner>> Attributes;
	/* This field has not had a description added. */
	TOptional<TSharedPtr<FJsonObject>> Data;
};

}
