/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIGetPlayerData200Response
 *
 * 
 */
class OPENAPI_API OpenAPIGetPlayerData200Response : public Model
{
public:
    virtual ~OpenAPIGetPlayerData200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TSharedPtr<FJsonObject>> ProtectedData;
	TOptional<TSharedPtr<FJsonObject>> PublicData;
};

}
