/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICreateContractRequest
 *
 * 
 */
class OPENAPI_API OpenAPICreateContractRequest : public Model
{
public:
    virtual ~OpenAPICreateContractRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The address of the existing contract. */
	FString Address;
	/* The address of the ERC2771 forwarding contract trusted by the contract. */
	TOptional<FString> ForwarderAddress;
	/* JSON of the abi. */
	FString Abi;
	enum class ChainEnum
	{
		Arbitrum,
		Arbitrumgoerli,
		Arbitrumnova,
		Avalanche,
		Avalanchefuji,
		Ethereum,
		Fantom,
		Fantomtest,
		Goerli,
		Matic,
		Maticmumbai,
		Thundercore,
		Thundercoretestnet,
  	};

	static FString EnumToString(const ChainEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ChainEnum& EnumValue);
	/* The blockchain you want to deploy this currency on. Support for new blockchains are added over time. */
	ChainEnum Chain;
};

}
