/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace MetaFab
{

/*
 * OpenAPIGetCurrencyFees200Response
 *
 * 
 */
class METAFAB_API OpenAPIGetCurrencyFees200Response : public Model
{
public:
    virtual ~OpenAPIGetCurrencyFees200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The wallet address that fees from all applicable transactions are automatically sent to. */
	TOptional<FString> RecipientAddress;
	/* The number of fee basis points. 100 basisPoints = 1% fee of the total transaction amount deducted from the total received by the recipient. */
	TOptional<double> BasisPoints;
	/* The fixed number of currency as a fee regardless of the total transaction amount. 10 = 10 of the currency as a fee for any transaction, deducted from the total received by the recipient. */
	TOptional<double> FixedAmount;
	/* The maximum combined fee between basisPoints and fixedAmount. If the total transaction fee is over this amount, the capAmount will be used as the transaction fee deducted from the total received by the recipient. */
	TOptional<double> CapAmount;
};

}
