/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace MetaFab
{

/*
 * OpenAPIBurnCollectionItemRequest
 *
 * 
 */
class METAFAB_API OpenAPIBurnCollectionItemRequest : public Model
{
public:
    virtual ~OpenAPIBurnCollectionItemRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The quantity of the collectionItemId to burn. */
	int32 Quantity = 0;
};

}
