/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICreateProfileRequest
 *
 * 
 */
class OPENAPI_API OpenAPICreateProfileRequest : public Model
{
public:
    virtual ~OpenAPICreateProfileRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The profile's username, used to authenticate the profile. Profile usernames are globally unique across MetaFab. There cannot be 2 profiles with the same username created. */
	FString Username;
	/* The password to authenticate as the profile. Additionally, this password is used to encrypt/decrypt a profile's primary wallet and must be provided anytime this profile makes blockchain interactions through various endpoints. */
	FString Password;
};

}
