/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace MetaFab
{

/*
 * OpenAPIUpdateGameRequest
 *
 * 
 */
class METAFAB_API OpenAPIUpdateGameRequest : public Model
{
public:
    virtual ~OpenAPIUpdateGameRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* A new name. Replaces the game's current name. */
	TOptional<FString> Name;
	/* A new email address. The game's old email will no longer be valid for account authentication. `currentPassword` must also be provided. */
	TOptional<FString> Email;
	/* The game's current password. Must be provided if setting `newPassword` or `email`. */
	TOptional<FString> CurrentPassword;
	/* A new password. The game's old password will no longer be valid. */
	TOptional<FString> NewPassword;
	/* Sets a custom RPC for your game to use instead of MetaFab's default RPCs for the chain(s) you specify.  Expects a JSON object containing key value pairs of supported `chain` -> `rpc url`. Only the chain names provided as keys in the object will be explicitly overriden. To delete a custom RPC for your game, provide the chain name to delete as a key in the provided object and `null` as the value.  Set RPC example, `{ MATIC: 'https://polygon-rpc.com' }` Delete RPC example, `{ MATIC: null }` */
	TOptional<TMap<FString, FString>> Rpcs;
	/* Revokes the game's previous published key and returns a new one if true. */
	TOptional<bool> ResetPublishedKey;
	/* Revokes the game's previous secret key and returns a new on if true. */
	TOptional<bool> ResetSecretKey;
};

}
