/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICreateEcosystemRequest
 *
 * 
 */
class OPENAPI_API OpenAPICreateEcosystemRequest : public Model
{
public:
    virtual ~OpenAPICreateEcosystemRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The name of the ecosystem you're creating. */
	FString Name;
	/* The email address associated with this ecosystem and used to login/authenticate as the ecosystem. */
	FString Email;
	/* The password to authenticate as the ecosystem. */
	FString Password;
};

}
