/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.2.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace MetaFab
{

/*
 * OpenAPITransferCurrencyRequest
 *
 * 
 */
class METAFAB_API OpenAPITransferCurrencyRequest : public Model
{
public:
    virtual ~OpenAPITransferCurrencyRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* A valid EVM based address to transfer currency to. For example, `0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D`. */
	TOptional<FString> Address;
	/* Any wallet id within the MetaFab ecosystem to transfer currency to. */
	TOptional<FString> WalletId;
	/* The amount of currency to transfer. */
	double Amount;
	/* An optional uint256 number to reference the transfer. Commonly used to identify transfers intended to pay for game items or services. */
	TOptional<double> Reference;
};

}
