/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPITransactionModel.h"

namespace OpenAPI
{

/*
 * OpenAPICreateCollection200ResponseAllOfContract
 *
 * 
 */
class OPENAPI_API OpenAPICreateCollection200ResponseAllOfContract : public Model
{
public:
    virtual ~OpenAPICreateCollection200ResponseAllOfContract() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* This field has not had a description added. */
	TOptional<FString> Id;
	/* This field has not had a description added. */
	TOptional<FString> GameId;
	/* This field has not had a description added. */
	TOptional<FString> Chain;
	/* This field has not had a description added. */
	TOptional<TSharedPtr<FJsonObject>> Abi;
	/* This field has not had a description added. */
	TOptional<FString> Type;
	/* This field has not had a description added. */
	TOptional<FString> Address;
	/* This field has not had a description added. */
	TOptional<FString> ForwarderAddress;
	/* This field has not had a description added. */
	TOptional<FString> UpdatedAt;
	/* This field has not had a description added. */
	TOptional<FString> CreatedAt;
	TOptional<TArray<OpenAPITransactionModel>> Transactions;
};

}
