/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.2.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIContractModel.h"

namespace MetaFab
{

/*
 * OpenAPIGetCurrencies200ResponseInnerAllOf
 *
 * 
 */
class METAFAB_API OpenAPIGetCurrencies200ResponseInnerAllOf : public Model
{
public:
    virtual ~OpenAPIGetCurrencies200ResponseInnerAllOf() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIContractModel> Contract;
};

}
