/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIWalletModel.h"

namespace OpenAPI
{

/*
 * OpenAPIAuthProfile200Response
 *
 * 
 */
class OPENAPI_API OpenAPIAuthProfile200Response : public Model
{
public:
    virtual ~OpenAPIAuthProfile200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* This field has not had a description added. */
	TOptional<FString> Id;
	/* This field has not had a description added. */
	TOptional<FString> EcosystemId;
	/* This field has not had a description added. */
	TOptional<FString> WalletId;
	/* This field has not had a description added. */
	TOptional<FString> ConnectedWalletId;
	/* This field has not had a description added. */
	TOptional<FString> Username;
	/* This field has not had a description added. */
	TOptional<FString> AccessToken;
	/* This field has not had a description added. */
	TOptional<FString> UpdatedAt;
	/* This field has not had a description added. */
	TOptional<FString> CreatedAt;
	/* This field has not had a description added. */
	TOptional<FString> WalletDecryptKey;
	TOptional<OpenAPIWalletModel> Wallet;
	TOptional<OpenAPIWalletModel> CustodialWallet;
};

}
