/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "MetaFabModule.h"

IMPLEMENT_MODULE(MetaFabModule, MetaFab);
DEFINE_LOG_CATEGORY(LogMetaFab);

void MetaFabModule::StartupModule()
{
}

void MetaFabModule::ShutdownModule()
{
}
