/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.4.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIRemovePlayerConnectedWalletRequest.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& Value)
{
	switch (Value)
	{
	case OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Ethereum:
		return TEXT("ETHEREUM");
	case OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Goerli:
		return TEXT("GOERLI");
	case OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Matic:
		return TEXT("MATIC");
	case OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Maticmumbai:
		return TEXT("MATICMUMBAI");
	case OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Arbitrum:
		return TEXT("ARBITRUM");
	case OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Arbitrumgoerli:
		return TEXT("ARBITRUMGOERLI");
	}

	UE_LOG(LogOpenAPI, Error, TEXT("Invalid OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIRemovePlayerConnectedWalletRequest::EnumToString(const OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& Value)
{
	static TMap<FString, OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum> StringToEnum = { 
		{ TEXT("ETHEREUM"), OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Ethereum },
		{ TEXT("GOERLI"), OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Goerli },
		{ TEXT("MATIC"), OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Matic },
		{ TEXT("MATICMUMBAI"), OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Maticmumbai },
		{ TEXT("ARBITRUM"), OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Arbitrum },
		{ TEXT("ARBITRUMGOERLI"), OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum::Arbitrumgoerli }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIRemovePlayerConnectedWalletRequest::EnumFromString(const FString& EnumAsString, OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIRemovePlayerConnectedWalletRequest::ChainEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIRemovePlayerConnectedWalletRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("address")); WriteJsonValue(Writer, Address);
	Writer->WriteIdentifierPrefix(TEXT("nonce")); WriteJsonValue(Writer, Nonce);
	Writer->WriteIdentifierPrefix(TEXT("signature")); WriteJsonValue(Writer, Signature);
	Writer->WriteIdentifierPrefix(TEXT("chain")); WriteJsonValue(Writer, Chain);
	Writer->WriteObjectEnd();
}

bool OpenAPIRemovePlayerConnectedWalletRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("address"), Address);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("nonce"), Nonce);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("signature"), Signature);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chain"), Chain);

	return ParseSuccess;
}

}
