/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.4.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIGetCurrencyFees200Response.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIGetCurrencyFees200Response::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (RecipientAddress.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("recipientAddress")); WriteJsonValue(Writer, RecipientAddress.GetValue());
	}
	if (BasisPoints.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("basisPoints")); WriteJsonValue(Writer, BasisPoints.GetValue());
	}
	if (FixedAmount.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("fixedAmount")); WriteJsonValue(Writer, FixedAmount.GetValue());
	}
	if (CapAmount.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("capAmount")); WriteJsonValue(Writer, CapAmount.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIGetCurrencyFees200Response::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("recipientAddress"), RecipientAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("basisPoints"), BasisPoints);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("fixedAmount"), FixedAmount);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("capAmount"), CapAmount);

	return ParseSuccess;
}

}
