/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPISetPlayerConnectedWalletRequest.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const OpenAPISetPlayerConnectedWalletRequest::ChainEnum& Value)
{
	switch (Value)
	{
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Arbitrum:
		return TEXT("ARBITRUM");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Arbitrumgoerli:
		return TEXT("ARBITRUMGOERLI");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Arbitrumnova:
		return TEXT("ARBITRUMNOVA");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Avalanche:
		return TEXT("AVALANCHE");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Avalanchefuji:
		return TEXT("AVALANCHEFUJI");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Ethereum:
		return TEXT("ETHEREUM");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Fantom:
		return TEXT("FANTOM");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Fantomtest:
		return TEXT("FANTOMTEST");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Goerli:
		return TEXT("GOERLI");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Matic:
		return TEXT("MATIC");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Maticmumbai:
		return TEXT("MATICMUMBAI");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Thundercore:
		return TEXT("THUNDERCORE");
	case OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Thundercoretestnet:
		return TEXT("THUNDERCORETESTNET");
	}

	UE_LOG(LogOpenAPI, Error, TEXT("Invalid OpenAPISetPlayerConnectedWalletRequest::ChainEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPISetPlayerConnectedWalletRequest::EnumToString(const OpenAPISetPlayerConnectedWalletRequest::ChainEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPISetPlayerConnectedWalletRequest::ChainEnum& Value)
{
	static TMap<FString, OpenAPISetPlayerConnectedWalletRequest::ChainEnum> StringToEnum = { 
		{ TEXT("ARBITRUM"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Arbitrum },
		{ TEXT("ARBITRUMGOERLI"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Arbitrumgoerli },
		{ TEXT("ARBITRUMNOVA"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Arbitrumnova },
		{ TEXT("AVALANCHE"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Avalanche },
		{ TEXT("AVALANCHEFUJI"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Avalanchefuji },
		{ TEXT("ETHEREUM"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Ethereum },
		{ TEXT("FANTOM"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Fantom },
		{ TEXT("FANTOMTEST"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Fantomtest },
		{ TEXT("GOERLI"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Goerli },
		{ TEXT("MATIC"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Matic },
		{ TEXT("MATICMUMBAI"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Maticmumbai },
		{ TEXT("THUNDERCORE"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Thundercore },
		{ TEXT("THUNDERCORETESTNET"), OpenAPISetPlayerConnectedWalletRequest::ChainEnum::Thundercoretestnet }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPISetPlayerConnectedWalletRequest::EnumFromString(const FString& EnumAsString, OpenAPISetPlayerConnectedWalletRequest::ChainEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPISetPlayerConnectedWalletRequest::ChainEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPISetPlayerConnectedWalletRequest::ChainEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPISetPlayerConnectedWalletRequest::ChainEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPISetPlayerConnectedWalletRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("address")); WriteJsonValue(Writer, Address);
	Writer->WriteIdentifierPrefix(TEXT("nonce")); WriteJsonValue(Writer, Nonce);
	Writer->WriteIdentifierPrefix(TEXT("signature")); WriteJsonValue(Writer, Signature);
	Writer->WriteIdentifierPrefix(TEXT("chain")); WriteJsonValue(Writer, Chain);
	Writer->WriteObjectEnd();
}

bool OpenAPISetPlayerConnectedWalletRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("address"), Address);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("nonce"), Nonce);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("signature"), Signature);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chain"), Chain);

	return ParseSuccess;
}

}
