/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICreateCurrencyRequest.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const OpenAPICreateCurrencyRequest::ChainEnum& Value)
{
	switch (Value)
	{
	case OpenAPICreateCurrencyRequest::ChainEnum::Arbitrum:
		return TEXT("ARBITRUM");
	case OpenAPICreateCurrencyRequest::ChainEnum::Arbitrumgoerli:
		return TEXT("ARBITRUMGOERLI");
	case OpenAPICreateCurrencyRequest::ChainEnum::Arbitrumnova:
		return TEXT("ARBITRUMNOVA");
	case OpenAPICreateCurrencyRequest::ChainEnum::Avalanche:
		return TEXT("AVALANCHE");
	case OpenAPICreateCurrencyRequest::ChainEnum::Avalanchefuji:
		return TEXT("AVALANCHEFUJI");
	case OpenAPICreateCurrencyRequest::ChainEnum::Ethereum:
		return TEXT("ETHEREUM");
	case OpenAPICreateCurrencyRequest::ChainEnum::Fantom:
		return TEXT("FANTOM");
	case OpenAPICreateCurrencyRequest::ChainEnum::Fantomtest:
		return TEXT("FANTOMTEST");
	case OpenAPICreateCurrencyRequest::ChainEnum::Goerli:
		return TEXT("GOERLI");
	case OpenAPICreateCurrencyRequest::ChainEnum::Matic:
		return TEXT("MATIC");
	case OpenAPICreateCurrencyRequest::ChainEnum::Maticmumbai:
		return TEXT("MATICMUMBAI");
	case OpenAPICreateCurrencyRequest::ChainEnum::Thundercore:
		return TEXT("THUNDERCORE");
	case OpenAPICreateCurrencyRequest::ChainEnum::Thundercoretestnet:
		return TEXT("THUNDERCORETESTNET");
	}

	UE_LOG(LogOpenAPI, Error, TEXT("Invalid OpenAPICreateCurrencyRequest::ChainEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPICreateCurrencyRequest::EnumToString(const OpenAPICreateCurrencyRequest::ChainEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPICreateCurrencyRequest::ChainEnum& Value)
{
	static TMap<FString, OpenAPICreateCurrencyRequest::ChainEnum> StringToEnum = { 
		{ TEXT("ARBITRUM"), OpenAPICreateCurrencyRequest::ChainEnum::Arbitrum },
		{ TEXT("ARBITRUMGOERLI"), OpenAPICreateCurrencyRequest::ChainEnum::Arbitrumgoerli },
		{ TEXT("ARBITRUMNOVA"), OpenAPICreateCurrencyRequest::ChainEnum::Arbitrumnova },
		{ TEXT("AVALANCHE"), OpenAPICreateCurrencyRequest::ChainEnum::Avalanche },
		{ TEXT("AVALANCHEFUJI"), OpenAPICreateCurrencyRequest::ChainEnum::Avalanchefuji },
		{ TEXT("ETHEREUM"), OpenAPICreateCurrencyRequest::ChainEnum::Ethereum },
		{ TEXT("FANTOM"), OpenAPICreateCurrencyRequest::ChainEnum::Fantom },
		{ TEXT("FANTOMTEST"), OpenAPICreateCurrencyRequest::ChainEnum::Fantomtest },
		{ TEXT("GOERLI"), OpenAPICreateCurrencyRequest::ChainEnum::Goerli },
		{ TEXT("MATIC"), OpenAPICreateCurrencyRequest::ChainEnum::Matic },
		{ TEXT("MATICMUMBAI"), OpenAPICreateCurrencyRequest::ChainEnum::Maticmumbai },
		{ TEXT("THUNDERCORE"), OpenAPICreateCurrencyRequest::ChainEnum::Thundercore },
		{ TEXT("THUNDERCORETESTNET"), OpenAPICreateCurrencyRequest::ChainEnum::Thundercoretestnet }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPICreateCurrencyRequest::EnumFromString(const FString& EnumAsString, OpenAPICreateCurrencyRequest::ChainEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPICreateCurrencyRequest::ChainEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPICreateCurrencyRequest::ChainEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPICreateCurrencyRequest::ChainEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPICreateCurrencyRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteIdentifierPrefix(TEXT("symbol")); WriteJsonValue(Writer, Symbol);
	Writer->WriteIdentifierPrefix(TEXT("supplyCap")); WriteJsonValue(Writer, SupplyCap);
	Writer->WriteIdentifierPrefix(TEXT("chain")); WriteJsonValue(Writer, Chain);
	Writer->WriteObjectEnd();
}

bool OpenAPICreateCurrencyRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("symbol"), Symbol);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("supplyCap"), SupplyCap);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chain"), Chain);

	return ParseSuccess;
}

}
