/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * OpenAPI spec version: 1.2.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICreateExchangeRequest.h"

#include "MetaFabModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace MetaFab
{

inline FString ToString(const OpenAPICreateExchangeRequest::ChainEnum& Value)
{
	switch (Value)
	{
	case OpenAPICreateExchangeRequest::ChainEnum::Ethereum:
		return TEXT("ETHEREUM");
	case OpenAPICreateExchangeRequest::ChainEnum::Goerli:
		return TEXT("GOERLI");
	case OpenAPICreateExchangeRequest::ChainEnum::Matic:
		return TEXT("MATIC");
	case OpenAPICreateExchangeRequest::ChainEnum::Maticmumbai:
		return TEXT("MATICMUMBAI");
	case OpenAPICreateExchangeRequest::ChainEnum::Arbitrum:
		return TEXT("ARBITRUM");
	case OpenAPICreateExchangeRequest::ChainEnum::Arbitrumgoerli:
		return TEXT("ARBITRUMGOERLI");
	}

	UE_LOG(LogMetaFab, Error, TEXT("Invalid OpenAPICreateExchangeRequest::ChainEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPICreateExchangeRequest::EnumToString(const OpenAPICreateExchangeRequest::ChainEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPICreateExchangeRequest::ChainEnum& Value)
{
	static TMap<FString, OpenAPICreateExchangeRequest::ChainEnum> StringToEnum = { 
		{ TEXT("ETHEREUM"), OpenAPICreateExchangeRequest::ChainEnum::Ethereum },
		{ TEXT("GOERLI"), OpenAPICreateExchangeRequest::ChainEnum::Goerli },
		{ TEXT("MATIC"), OpenAPICreateExchangeRequest::ChainEnum::Matic },
		{ TEXT("MATICMUMBAI"), OpenAPICreateExchangeRequest::ChainEnum::Maticmumbai },
		{ TEXT("ARBITRUM"), OpenAPICreateExchangeRequest::ChainEnum::Arbitrum },
		{ TEXT("ARBITRUMGOERLI"), OpenAPICreateExchangeRequest::ChainEnum::Arbitrumgoerli }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPICreateExchangeRequest::EnumFromString(const FString& EnumAsString, OpenAPICreateExchangeRequest::ChainEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPICreateExchangeRequest::ChainEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPICreateExchangeRequest::ChainEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPICreateExchangeRequest::ChainEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPICreateExchangeRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("chain")); WriteJsonValue(Writer, Chain);
	Writer->WriteObjectEnd();
}

bool OpenAPICreateExchangeRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chain"), Chain);

	return ParseSuccess;
}

}
